indir: no  # to be overriden in CLI
outdir: no  # to be overriden in CLI

model:
  path: lama/big-lama  # to be overriden in CLI
  checkpoint: best.ckpt

dataset:
  kind: default
  img_suffix: .jpg
  pad_out_to_modulo: 8

device: cuda
out_key: inpainted
