generator_kind: segmentation

mask_generator_kwargs:
  confidence_threshold: 0.5
  max_object_area: 0.5
  min_mask_area: 0.02
  downsample_levels: 6
  num_variants_per_mask: 5
  rigidness_mode: 1
  max_foreground_coverage: 0.3
  max_foreground_intersection: 0.7
  max_mask_intersection: 0.1
  max_hidden_area: 0.1
  max_scale_change: 0.25
  horizontal_flip: True
  max_vertical_shift: 0.2
  position_shuffle: True

max_masks_per_image: 5

cropping:
  out_min_size: 512
  handle_small_mode: drop
  out_square_crop: True
  crop_min_overlap: 0.5
