generator_kind: random

mask_generator_kwargs:
  irregular_proba: 0
  box_proba: 0
  segm_proba: 0
  squares_proba: 0
  superres_proba: 1
  superres_kwargs:
    min_step: 2
    max_step: 4
    min_width: 1
    max_width: 3

  variants_n: 5

max_masks_per_image: 1

cropping:
  out_min_size: 256
  handle_small_mode: upscale
  out_square_crop: True
  crop_min_overlap: 1

max_tamper_area: 1
